### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by alfari24** [Lauwy222/UptimeKuma-DiscordBot#1]
this amazing integration uptime kuma with discord, so we can monitoring our service without see the website.
can you add one information about ping /ms, on api i see we can add using 'monitor_response_time', thats will be really great.

**Comment by Lauwy222** [comment]
Hey, we currently only read out `monitor_status` for this to work we need to read out `monitor_response_time`. I currently only run docker containers which I monitor. Since I can't test is I would guess you need to add this:
```JS
if ($http_status == 200) {
    // Parse the response and extract relevant data
    preg_match_all('/monitor_response_time\{(.*?)\} (\d+)/', $response, $matches, PREG_SET_ORDER);
    
    $data = [];
    // Loop through each match
    foreach ($matches as $match) {
        $labels = [];
        // Split the match into parts
        $parts = explode(',', $match[1]);
        // Loop through each part
        foreach ($parts as $part) {
            // Split the part into key and value
            list($key, $value) = explode('=', $part);
            // Trim and store the key-value pair
            $labels[trim($key)] = trim($value, '"');
        }
        // Add the parsed data to the data array
        $data[] = [
            'monitor_name' => $labels['monitor_name'],
            'monitor_type' => $labels['monitor_type'],
            'monitor_url' => $labels['monitor_url'],
            'monitor_hostname' => $labels['monitor_hostname'],
            'monitor_port' => $labels['monitor_port'],
            'ping' => (int) $match[2]
        ];
    }
```
To the web to read the monitor resonse and then you'll need to add another ASYNC check in the Discord bot, You can add it if you want to ;)

**Comment by alfari24** [comment]
It's worked, thanks
![image](https://github.com/user-attachments/assets/bafa2d5b-d867-4dae-b935-5c020cba8907)
